main: #basic config
  appname: first_blood_server
  request:
    sig_keys:
      '1': "i am ios"
      '2': "i am android"
  redis:
    host: 'localhost'
    port: '6379'
  log:
      name: first_blood_server
      stdout: true
      level: debug
      facility: 1

first_blood:

