flask:
  app:
    secret_key: "real secret"
    session_cookie_name: "SID"
    permanent_session_lifetime: 86400
  session:
    type: "redis"
    redis:
      host: "127.0.0.1"
      port: 6379
      db: 0
    key_prefix: "commerce:"
